### ISSUE TITLE
Load to-do tiles from database

### ISSUE THREAD

**Issue by Stuflo19** [Stuflo19/android_app#11]
Read in data from the database table to generate the user's to-do tiles and an overview of their task

As a user of this app,
I want to be able to have my submitted tasks loaded back to me,
So that I can view them again and remember my tasks.

**A/C**
- [x] Open connection to database
- [x] Read in data from the database
- [x] Display data on the to-do tile templates

**Comment by Stuflo19** [comment]
Added setup function to homepage that reads in tiles from database and a for loop to print a new tile for every tile read from the database
