### ISSUE TITLE
Create to-do page

### ISSUE THREAD

**Issue by Stuflo19** [Stuflo19/android_app#8]
Create new page for to-do tiles that can show a list if to-do items with a button that would allow later functionality of adding a new to-do item and interaction with the tiles that could allow future functionality of opening a more detailed page.

As a user of this app,
I would like to see a list of my to-do items,
so that I can quickly see what items I have made.

**A/C**
- [x] Tiles can be presented to the user.
- [x] Tiles can be interacted with (no functionality implemented yet).
- [x] A button appears in the bottom right for adding a new tile (no functionality implemented yet).
- [x] Tiles become scrollable when off the bottom of the screen.
- [x] Tiles expand when a lot of text is included.
